import { Injectable } from '@nestjs/common';
import { User } from '../domain/user.entity';
import { IUserRepository } from '../domain/user.repository.interface';
import { ITokenService } from '../domain/token.service.interface';
import {
  IAuthUseCase,
  RegisterRequest,
  RegisterResponse,
  LoginRequest,
  LoginResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  GetMeResponse,
} from '../domain/auth.usecase.interface';
import { PasswordUtil } from '@core/utils/password.util';
import {
  ConflictException,
  UnauthorizedException,
  NotFoundException,
  ValidationException,
} from '@core/exceptions/exceptions';
import { InMemoryUserRepository } from '../infrastructure/in-memory-user.repository';
import { JwtTokenService } from '../infrastructure/jwt-token.service';

/**
 * Auth Use Case Implementation
 * 
 * This class contains all authentication business logic.
 * It orchestrates between the Domain (User entity) and Infrastructure (repositories, services).
 * 
 * WHY: 
 * - Separates business logic from HTTP layer (controllers)
 * - Can be reused by different interfaces (REST, GraphQL, gRPC, etc.)
 * - Easy to test in isolation
 * - Dependencies are injected, making it flexible and testable
 */
@Injectable()
export class AuthUseCase implements IAuthUseCase {
  constructor(
    private readonly userRepository: InMemoryUserRepository,
    private readonly tokenService: JwtTokenService,
  ) {}

  /**
   * Register a new user
   * 
   * Steps:
   * 1. Validate input
   * 2. Check if email already exists
   * 3. Hash password
   * 4. Create user entity
   * 5. Persist to database
   * 6. Return user data (without password)
   */
  async register(request: RegisterRequest): Promise<RegisterResponse> {
    // Validate password strength
    const passwordValidation = PasswordUtil.validatePasswordStrength(
      request.password,
    );
    if (!passwordValidation.isValid) {
      throw new ValidationException('Password does not meet requirements', {
        password: passwordValidation.errors,
      });
    }

    // Check if email already exists
    const existingUser = await this.userRepository.findByEmail(request.email);
    if (existingUser) {
      throw new ConflictException('Email already registered');
    }

    // Hash password
    const hashedPassword = await PasswordUtil.hash(request.password);

    // Create user entity
    const user = new User(
      undefined as any, // ID will be generated by entity
      request.email,
      hashedPassword,
      request.firstName,
      request.lastName,
    );

    // Persist to repository
    const createdUser = await this.userRepository.create(user);

    // Return user data (never return password)
    return {
      id: createdUser.id,
      email: createdUser.email,
      firstName: createdUser.firstName,
      lastName: createdUser.lastName,
      createdAt: createdUser.createdAt,
    };
  }

  /**
   * Login user
   * 
   * Steps:
   * 1. Find user by email
   * 2. Verify password
   * 3. Update last login time
   * 4. Generate tokens
   * 5. Return tokens and user info
   */
  async login(request: LoginRequest): Promise<LoginResponse> {
    // Find user
    const user = await this.userRepository.findByEmail(request.email);
    if (!user) {
      throw new UnauthorizedException('Invalid email or password');
    }

    // Verify password
    const isPasswordValid = await PasswordUtil.compare(
      request.password,
      user.password,
    );
    if (!isPasswordValid) {
      throw new UnauthorizedException('Invalid email or password');
    }

    // Check if user is active
    if (!user.isActive) {
      throw new UnauthorizedException('User account is inactive');
    }

    // Record login time
    user.recordLogin();
    await this.userRepository.update(user);

    // Generate tokens
    const accessToken = await this.tokenService.generateAccessToken(
      user.id,
      user.email,
    );
    const refreshToken = await this.tokenService.generateRefreshToken(user.id);

    return {
      accessToken,
      refreshToken,
      user: {
        id: user.id,
        email: user.email,
        firstName: user.firstName,
        lastName: user.lastName,
      },
    };
  }

  /**
   * Refresh access token using refresh token
   */
  async refreshToken(request: RefreshTokenRequest): Promise<RefreshTokenResponse> {
    try {
      // Verify refresh token
      const payload = await this.tokenService.verifyRefreshToken(
        request.refreshToken,
      );

      // Find user
      const user = await this.userRepository.findById(payload.userId);
      if (!user) {
        throw new NotFoundException('User not found');
      }

      // Generate new tokens
      const newAccessToken = await this.tokenService.generateAccessToken(
        user.id,
        user.email,
      );
      const newRefreshToken = await this.tokenService.generateRefreshToken(
        user.id,
      );

      return {
        accessToken: newAccessToken,
        refreshToken: newRefreshToken,
      };
    } catch (error) {
      throw new UnauthorizedException('Invalid refresh token');
    }
  }

  /**
   * Logout user
   * In this simple implementation, logout is handled on client side
   * by removing tokens. In production, you might want to:
   * - Blacklist tokens
   * - Store refresh tokens in database
   * - Track user sessions
   */
  async logout(userId: string): Promise<void> {
    // In a production app:
    // 1. Add token to blacklist
    // 2. Invalidate user sessions
    // 3. Clear refresh tokens from database
    // For now, this is a placeholder
  }

  /**
   * Get current user information
   */
  async getMe(userId: string): Promise<GetMeResponse> {
    const user = await this.userRepository.findById(userId);
    if (!user) {
      throw new NotFoundException('User not found');
    }

    return {
      id: user.id,
      email: user.email,
      firstName: user.firstName,
      lastName: user.lastName,
      createdAt: user.createdAt,
      updatedAt: user.updatedAt,
    };
  }
}
